# Generated by Django 5.2 on 2025-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bidding_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
