# Generated by Django 5.2 on 2025-04-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
