# Generated by Django 5.2 on 2025-04-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_user_auction_winner_alter_auction_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
    ]
