# Generated by Django 5.2 on 2025-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
